[ Automated import by raw2svndump ]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -845,6 +845,8 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-noselect-default
+                          default to not using select(2)
   --enable-track-default=PORT|ID
                           default to tracking probes by PORT or ID
   --enable-default-port=N default destination port
@@ -3670,7 +3672,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_SOCKADDR_SA_LEN
+#define HAVE_SOCKADDR_SA_LEN 1
 _ACEOF
 
 
@@ -4654,7 +4656,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
 echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_SOLARIS
+#define HAVE_SOLARIS 1
 _ACEOF
 
 		HAVE_SOLARIS=yes
@@ -4671,6 +4673,98 @@ echo "${ECHO_T}no" >&6
 
 fi
 rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+# Is this MacOS X?
+echo "$as_me:$LINENO: checking for MacOS X" >&5
+echo $ECHO_N "checking for MacOS X... $ECHO_C" >&6
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+#if defined (__APPLE__) && defined (__MACH__)
+	exit(0);
+#else
+	exit(-1);
+#endif
+
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MACOSX 1
+_ACEOF
+
+		HAVE_MACOSX=yes
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+# Handle --enable-noselect-default
+# Check whether --enable-noselect-default or --disable-noselect-default was given.
+if test "${enable_noselect_default+set}" = set; then
+  enableval="$enable_noselect_default"
+
+		NOSELECT_DEFAULT=$enable_noselect_default
+
+else
+
+		if test "$HAVE_MACOSX" = "yes"; then
+			NOSELECT_DEFAULT=yes
+		else
+			NOSELECT_DEFAULT=no
+		fi
+
+fi;
+if test "$NOSELECT_DEFAULT" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define NOSELECT_DEFAULT 1
+_ACEOF
+
 fi
 
 # Handle --enable-track-default=IP|PORT
@@ -4700,13 +4794,13 @@ fi;
 if test "$TRACK_DEFAULT" = "port"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define TRACK_PORT_DEFAULT
+#define TRACK_PORT_DEFAULT 1
 _ACEOF
 
 else
 
 cat >>confdefs.h <<\_ACEOF
-#define TRACK_ID_DEFAULT
+#define TRACK_ID_DEFAULT 1
 _ACEOF
 
 fi
